Console.Clear();
Console.WriteLine("Введите значение b1:");
double b1 = Convert.ToDouble(Console.ReadLine());
Console.WriteLine("Введите значение k1:");
double k1 = Convert.ToDouble(Console.ReadLine());
Console.WriteLine("Введите значение b2:");
double b2 = Convert.ToDouble(Console.ReadLine());
Console.WriteLine("Введите значение k2:");
double k2 = Convert.ToDouble(Console.ReadLine());
double y = (b2 / b1) / (k1 - k2);
double x = (y - b1) / k1;
Console.WriteLine($" Y равен = {y}");
Console.WriteLine($" Y равен = {x}");